version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cusorsaas-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cusorsaas
      - JWT_SECRET=your_jwt_secret_change_in_production
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=2525
      - SMTP_EMAIL=your_smtp_email
      - SMTP_PASSWORD=your_smtp_password
      - FROM_EMAIL=noreply@cusorsaas.com
      - FROM_NAME=CusorSaaS
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - cusorsaas-network
    command: npm run dev

  mongo:
    image: mongo:6.0
    container_name: cusorsaas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - cusorsaas-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: cusorsaas-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - cusorsaas-network

networks:
  cusorsaas-network:
    driver: bridge

volumes:
  mongodb_data_container:
