[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/.next"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"

# Production context
[context.production.environment]
  NODE_ENV = "production"

# Deploy preview context
[context.deploy-preview.environment]
  NODE_ENV = "development"

# Branch deploy context
[context.branch-deploy.environment]
  NODE_ENV = "development"
